name: 'Sonarqube Python Scanner'
description: 'Quality Gate Sonarqube for Python projects'

inputs:
  sonar-verbose:
    required: false
    type: boolean
    default: false
  sonar-sources:
    required: false
    type: string
    default: "src"
  sonar-sources-tests:
    required: false
    type: string
    default: "tests"
  sonar-test-inclusions:
    required: false
    type: string
    default: "**/test_*.py,**/*_test.py,**/__pycache__/**,**/__init__.py"
  sonar-report-paths:
    required: false
    type: string
    default: "coverage.xml"
  sonar-source-encoding:
    required: false
    type: string
    default: "UTF-8"
  sonar-exclusions:
    required: false
    type: string
    default: "**/__pycache__/**,**/*.pyc,**/migrations/**,
    **/fixtures/**,**/.venv/**,**/.git/**,**/.vscode/**,**/*.html,**/htmlcov/**,coverage.xml"
  sonar-lang:
    required: false
    type: string
    default: "python"
  sonar-lang-version:
    required: false
    type: string
  sonar-token:
    type: string
  sonar-host-url:
    type: string
  sonar-api-token:
    type: string

runs:
  using: composite
  steps:
    - name: Push to RubyGems
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        RUBYGEMS_API_KEY: ${{ inputs.rubygems_api_key }}
    - name: SonarQube Scan
      if: |
        github.base_ref == 'develop' &&
        inputs.sonar-enable == true &&
        inputs.sonar-lang == 'python'
      uses: sonarsource/sonarqube-scan-action@v5.2.0
      continue-on-error: true
      with:
        args: >
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.sources=${{ inputs.sonar-sources }}
          -Dsonar.tests=${{ inputs.sonar-sources-tests }}
          -Dsonar.test.inclusions=${{inputs.sonar-test-inclusions }}
          -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
          -Dsonar.python.version=${{ inputs.sonar-lang-version }}
          -Dsonar.python.coverage.reportPaths=${{ inputs.sonar-report-paths }}
          -Dsonar.verbose=${{ inputs.sonar-verbose }}
          -Dsonar.sourceEncoding=${{ inputs.sonar-source-encoding }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}

    - name: Check SonarQube Quality Gate Status
      id: sonarqube-status
      if: github.base_ref == 'develop' && inputs.sonar-enable == true
      continue-on-error: true
      run: ${{ github.action_path }}/sonarqube-status.sh
      env:
        SONAR_TOKEN: ${{ inputs.sonar-api-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}

    - name: Get Coverage
      id: coverage-calc
      if: steps.sonarqube-status.outputs.status == 'OK'
      continue-on-error: true
      run: ${{ github.action_path }}/coverage-calc.sh

    - name: Update Quality Gates Sonarqube
      id: quality-gates-sonarqube
      if: steps.sonarqube-status.outputs.status == 'OK'
      continue-on-error: true
      run: ${{ github.action_path }}/quality-gates-sonarqube.sh
      env:
        SONAR_TOKEN: ${{ inputs.sonar-api-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
