name: Create Env
description: Create Env

inputs:
  ref_name:
    required: true
    description: ref_name
  project_id:
    required: true
    description: project_id
  safe_ips:
    required: true
    description: safe_ips
runs:
  using: composite
  steps:
    - name: Create Env
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        GITHUB_REF_NAME: ${{ inputs.ref_name }}
        GOOGLE_PROJECTID: ${{ inputs.project_id}}
        JKS_SAFE_IPS: ${{ inputs.safe_ips }}
