name: 'Install Python System Packages (Linux)'
description: 'Install system packages required for Python builds on self-hosted Linux runners.'

inputs:
  runs-on:
    required: false
    type: string
    default: 'self-hosted'
  python-version:
    required: false
    type: string
    default: ''

runs:
  using: composite
  steps:
    - name: Install system packages (Linux)
      if: ${{ inputs.runs-on == 'self-hosted' && runner.os == 'Linux' && inputs.python-version != '' }}
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
